changelog/fourteen_guamp.txt, gapps/guamp.json
Change-Id: I2004d086f35e0c35125d8e6f0945af14f2a13fdc
=> update: moto g9/play 20/05/2024

changelog/fourteen_marble.txt, gapps/marble.json, vanilla/marble.json
Kindly merge this PR for marble Infinity-X 1.1 Update 02.06.2024
=> marble: Infinity-X 1.1 Update 02.06.2024

changelog/fourteen_marble.txt, gapps/marble.json, vanilla/marble.json
Kindly merge the PR for marble Infinity-X 1.2 Update 23.06.2024
=> marble: Infinity-X 1.2 Update 23.06.2024

changelog/fourteen_marble.txt
merge this PR for marble: Changelog for Infinity X 1.3 Update - 09.07.24
=> marble: Changelog for Infinity X 1.3 Update - 09.07.24

changelog/fourteen_marble.txt, gapps/marble.json, vanilla/marble.json
Kindly merge this PR for marble: Infinity X v1.3 Hotfix Update 11.07.24
=> marble: Infinity X v1.3 Hotfix Update 11.07.24

changelog/fourteen_tundra.txt, gapps/tundra.json
First release of Project Infinity X for Motorola Edge 30 fusion (tundra)
=> tundra: Initial Build

changelog/fourteen_tundra.txt, gapps/tundra.json
Update for source side changes
=> tundra: incremental update

changelog/fourteen_alioth.txt, gapps/alioth.json, vanilla/alioth.json
=> alioth: 16/09/2024 update

gapps/spes.json
An Hotfix Update That Fixes the Sensors!
=>  spes: v1.6 16.10.2024 hotfix update.

changelog/beryllium.txt, devices/beryllium.json, flashguide/beryllium.txt, gapps/beryllium.json
Signed-off-by: Akshat <Legendleo90@users.noreply.github.com>
=> beryllium: 11/12/2024 Update

changelog/cheetah.txt, changelog/panther.txt, devices/panther.json, gapps/cheetah.json, gapps/panther.json
=> panther: Initial Android 15 release

changelog/garnet.txt, devices/garnet.json, gapps/garnet.json, vanilla/garnet.json
=> garnet: 26/01/2025 Update

changelog/munch.txt, flashguide/munch.txt, gapps/munch.json, vanilla/munch.json
=> munch: v2.4 Update

changelog/beryllium.txt, gapps/beryllium.json
Signed-off-by: Akshat <Legendleo90@users.noreply.github.com>
=> beryllium: 09/02/2025 Update

changelog/sweet.txt, devices/sweet.json, gapps/sweet.json
- this is all you've been waiting for
=> sweet: 15/02/2025 update

changelog/hotdogb.txt, devices/hotdogb.json, flashguide/hotdogb.txt, gapps/hotdogb.json
=> hotdogb: 04/12/2025 release

changelog/fogos.txt, gapps/fogos.json, vanilla/fogos.json
It's a stable update with no bugs
=> fogos: 17.04.2025 update for fogos

changelog/sweet.txt, devices/sweet.json, gapps/sweet.json
=> sweet: 20/04/2025 update

changelog/raphael.txt, devices/raphael.json, flashguide/raphael.txt, gapps/raphael.json, vanilla/raphael.json
=> raphael: v2.8 Update | 9/05/2025

gapps/husky.json
Fixup Mismatched Dates via Husky
=> Pixel 8 Series: Fixup! 21/05/2025 Hotfix {May-ARB}

changelog/fogos.txt, gapps/fogos.json, vanilla/fogos.json
Late pushing due to some health issues
=> fogos: 01.06.2025 update

gapps/spes.json
For Project Infinity Update v2.9. There are no other changes on device side.
=> spes: Update v2.9

gapps/spes.json
=> spes :Update v2.9 Hotfix

changelog/redwood.txt, devices/redwood.json, flashguide/redwood.txt, gapps/redwood.json
Committer: RDX463 <balsarafrohan627@gmail.com>
=> redwood: 14/07/25 update

changelog/beryllium.txt, devices/beryllium.json, flashguide/beryllium.txt, gapps/beryllium.json, vanilla/beryllium.json
* Also Update maintainer details
=> beryllium: 03/10/25 v3.2 Update
